# Generated by Django 6.0.7 on 2026-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='original_URL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
