# Generated by Django 6.0.7 on 2026-08-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0002_alter_recipe_original_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
