# Generated by Django 6.0.7 on 2026-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseredSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('parser_name', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ('url',),
            },
        ),
    ]
