# Generated by Django 6.1 on 2026-09-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0005_parseredsites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ingredient_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_form', models.TextField(unique=True)),
                ('ingredient_correct_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeSite.ingredients_set')),
            ],
        ),
    ]
