# Generated by Django 6.1 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0006_ingredients_set_ingredient_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseredsites',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_URL',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
