# Generated by Django 6.1 on 2026-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0007_alter_parseredsites_url_alter_recipe_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
