# Generated by Django 6.1 on 2026-09-02 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0008_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('colour', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите HEX-код цвета (например, #FF0000 или #F00)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parseredsites',
            name='parser_name',
            field=models.TextField(blank=True, default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_URL',
            field=models.TextField(blank=True, default=None, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeSite.ingredients_set')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeSite.recipe')),
            ],
            options={
                'verbose_name': 'Связь рецепта и ингредиента',
                'verbose_name_plural': 'Связь рецептов и ингредиентов',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='RecipeSite.subtag'),
        ),
        migrations.AddField(
            model_name='subtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeSite.tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipies', through='RecipeSite.RecipeIngredient', to='RecipeSite.ingredients_set'),
        ),
    ]
