# Generated by Django 6.1 on 2026-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0009_subtag_tag_rename_user_recipe_autor_recipe_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipies', to='RecipeSite.subtag'),
        ),
    ]
