# Generated by Django 6.1 on 2026-09-02 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0011_alter_recipe_likes_alter_recipeingredient_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.TextField(default='defoult', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='extra',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='IngredientSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('rejected', 'отклонено'), ('accepted', 'разрешено')], default='pending', max_length=20, verbose_name='Статус')),
                ('added_at', models.DateField(auto_now_add=True)),
                ('moderated_at', models.DateField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложить ингридиент',
                'verbose_name_plural': 'Предложения ингридиентов',
                'ordering': ('-added_at', 'moderated_at'),
            },
        ),
        migrations.CreateModel(
            name='SuggestNewIngredientForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_forms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forms', to='RecipeSite.ingredientsuggestion')),
            ],
            options={
                'verbose_name': 'Новая форма',
                'verbose_name_plural': 'Новые формы',
            },
        ),
    ]
