# Generated by Django 6.1 on 2026-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0012_rename_ingredient_recipeingredient_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
