# Generated by Django 6.1 on 2026-09-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0013_alter_recipeingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestnewingredientforms',
            name='ingredient_forms',
        ),
        migrations.AddField(
            model_name='ingredientsuggestion',
            name='forms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RecipeSite.suggestnewingredientforms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestnewingredientforms',
            name='ingredient_form',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
