# Generated by Django 6.1 on 2026-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0014_remove_suggestnewingredientforms_ingredient_forms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(blank=True),
        ),
    ]
