# Generated by Django 6.1 on 2026-09-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0015_recipe_recipe_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_url',
            new_name='recipe_img_url',
        ),
    ]
