# Generated by Django 6.1 on 2026-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0018_alter_recipeingredient_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
