# Generated by Django 6.1 on 2026-09-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0022_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsuggestion',
            old_name='ingredient_id',
            new_name='normal_form',
        ),
        migrations.RemoveField(
            model_name='ingredientsuggestion',
            name='forms',
        ),
        migrations.AddField(
            model_name='suggestnewingredientforms',
            name='suggestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='RecipeSite.ingredientsuggestion'),
            preserve_default=False,
        ),
    ]
