# Generated by Django 6.1 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeSite', '0023_rename_ingredient_id_ingredientsuggestion_normal_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsuggestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='ingredientsuggestion',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
